### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ChipTheProto** [TonyGamer/LipsyncHelper#2]
With the Unity 2022 Editor update I get:

NullReferenceException: Object reference not set to an instance of an object
LipsyncToAnim.Convert () (at Assets/LipsyncToAnim/LipsyncToAnim.cs:83)
LipsyncToAnim.OnValidate () (at Assets/LipsyncToAnim/LipsyncToAnim.cs:53)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

after clicking convert. Used it a bunch on 2019 with no problems.

**Comment by AdalynBlack** [comment]
It looks like Oculus's OVR Lipsync package may have been updated
I'll have a look at it and try to update it

**Comment by ChipTheProto** [comment]
Weird cause I used the same package for it that I downloaded a year ago when I found this wonderful plugin.

**Comment by ChipTheProto** [comment]
Any luck on this?

**Comment by Mirasaru** [comment]
I would also like to know if there is any news on this. the asset doesnt work on 2022 and the 2019 unity for vrchat has been obsolete

**Comment by ChipTheProto** [comment]
> I would also like to know if there is any news on this. the asset doesnt work on 2022 and the 2019 unity for vrchat has been obsolete

What I've been doing in the meantime is pulling the model into an old project and running the script then moving the anim file back to the newer one for upload.

**Comment by AdalynBlack** [comment]
So sorry I haven't worked on this for a while. I've been busy with school and such for a while now, but I should be free to fix the problem now. It might be a day or two before I get a chance to take a look, but I'll definitely have a look when I have a chance

**Comment by AdalynBlack** [comment]
I'm trying to recreate the issue on my end and it seems to work just fine. Could you verify the issue with a fresh project and installation, using the latest version of the OVRLipSync package? The core of the issue seems to be related to OVRLipSync failing to generate any lipsync data for the input audio from what I can tell

**Comment by Mirasaru** [comment]
the issue is the exact same as what was posted in december, NullReferenceException: Object reference not set to an instance of an object. i installed the latest version of ovrlipsync but so far nothing

**Comment by AdalynBlack** [comment]
I see
could you try the demo scene, and if that fails, could you try cloning the git repo and upgrading it to Unity 2022?

**Comment by ChipTheProto** [comment]
> the issue is the exact same as what was posted in december, NullReferenceException: Object reference not set to an instance of an object. i installed the latest version of ovrlipsync but so far nothing

Same. Tested in 2022.3.22f.

**Comment by ChipTheProto** [comment]
> I see could you try the demo scene, and if that fails, could you try cloning the git repo and upgrading it to Unity 2022?

Demo scene succeeds but continues to fail with any other avatar.

**Comment by AdalynBlack** [comment]
I see
could you send me the audio clip that's causing issues?

**Comment by ChipTheProto** [comment]
I used the audio clip included in the demo for the latest test but this error was on me for having the script in the wrong place. It converts with the provided sample audio but when the audio is changed to any other clip, back to the old error.

**Comment by AdalynBlack** [comment]
ohh I found the issue
Enable "Preload Audio Data" on the audio file. Newer Unity versions seem to import with that disabled by default. I'll push a fix that loads the data if it's not already loaded

**Comment by ChipTheProto** [comment]
Can confirm, that was it! Yay, glad it wasn't anything major.

**Comment by AdalynBlack** [comment]
Ok, this issue is now officially resolved. As of Version 0.2.3, the script will now load the audio if it isn't already loaded
